ARG FRR_VERSION=10.2.1
ARG UBUNTU_VERSION=jammy

FROM ubuntu:${UBUNTU_VERSION} AS builder
ARG FRR_VERSION

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    autoconf \
    automake \
    bison \
    flex \
    libcap-dev \
    libelf-dev \
    libjson-c-dev \
    libmnl-dev \
    libncurses-dev \
    libnftnl-dev \
    libnl-3-dev \
    libnl-route-3-dev \
    libpcre2-dev \
    libreadline-dev \
    libsnmp-dev \
    libssl-dev \
    libsystemd-dev \
    libtool \
    pkg-config \
    python3-dev \
    python3-pip \
    protobuf-compiler \
    protobuf-c-compiler \
    git \
    curl \
    ca-certificates \
    iproute2 \
    rsync \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

RUN curl -fsSL "https://github.com/FRRouting/frr/archive/refs/tags/frr-${FRR_VERSION}.tar.gz" -o /tmp/frr.tar.gz \
    && tar -xzf /tmp/frr.tar.gz -C /src --strip-components=1

RUN ./bootstrap.sh

RUN ./configure \
    --prefix=/usr/local \
    --sbindir=/usr/local/bin \
    --sysconfdir=/etc/frr \
    --localstatedir=/var/run/frr \
    --enable-vtysh \
    --enable-bgp \
    --enable-zebra \
    --disable-ospfd \
    --disable-ospf6d \
    --disable-isisd \
    --disable-ripd \
    --disable-ripngd \
    --disable-pimd \
    --disable-ldpd \
    --disable-nhrpd \
    --disable-bfdd \
    --disable-staticd \
    --disable-vrrpd \
    --disable-sharpd \
    --disable-pbrd \
    --disable-fabricd \
    --enable-user=frr \
    --enable-group=frr \
    --enable-configfile-mask=0640 \
    --with-vty-group=frrvty \
    --with-pkg-extra-version=akley-sidecar \
    --enable-systemd \
    --enable-snmp \
    --enable-dev-build

RUN make -j4 \
    && make install

FROM ubuntu:${UBUNTU_VERSION}
ARG FRR_VERSION

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC \
    FRR_VERSION=${FRR_VERSION}

RUN apt-get update && apt-get install -y --no-install-recommends \
    iproute2 \
    ca-certificates \
    libcap2 \
    libelf1 \
    libjson-c5 \
    libmnl0 \
    libncurses6 \
    libnftnl11 \
    libnl-3-200 \
    libnl-route-3-200 \
    libpcre2-8-0 \
    libprotobuf-c1 \
    libreadline8 \
    libsnmp40 \
    libssl3 \
    libsystemd0 \
    procps \
    tini \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -r frr --gid 101 \
    && useradd -r -g frr -d /var/run/frr -s /usr/sbin/nologin -u 101 frr \
    && mkdir -p /etc/frr /var/log/frr /var/run/frr /var/lib/frr \
    && chown -R frr:frr /etc/frr /var/log/frr /var/run/frr /var/lib/frr

COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /usr/local/sbin/ /usr/local/sbin/
COPY --from=builder /usr/local/share/ /usr/local/share/
COPY --from=builder /usr/local/lib/ /usr/local/lib/
COPY --from=builder /etc/frr/ /etc/frr/

RUN cat > /docker-entrypoint.sh <<'EOF'
#!/bin/sh
set -eu

: "${FRR_CONF_DIR:=/etc/frr}"
: "${FRR_DAEMONS:=bgpd zebra}"

mkdir -p "${FRR_CONF_DIR}"

if [ ! -f "${FRR_CONF_DIR}/daemons" ]; then
    cat > "${FRR_CONF_DIR}/daemons" <<'DAEMONS'
# Auto-generated by Docker image
zebra=yes
bgpd=yes
ospfd=no
ospf6d=no
isisd=no
ripd=no
ripngd=no
pimd=no
ldpd=no
nhrpd=no
bfdd=no
staticd=no
vrrpd=no
sharpd=no
pbrd=no
fabricd=no
vtysh_enable=yes
DAEMONS
fi

# If a user-supplied config exists, use it; otherwise leave FRR defaults.
# This image is intended to run as a BGP sidecar in a Kubernetes pod.
exec /usr/bin/tini -- /usr/local/bin/frr -d
EOF

RUN chmod 755 /docker-entrypoint.sh

EXPOSE 179 2601 2602 2603 2604 2605 2606 2607 2608 2609 2610

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD []
